pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }  // For JSch fork (decent-player SFTP support)
    }
}

gradle.ext.androidxMediaModulePrefix = 'media-'
gradle.ext.androidxMediaProjectName = 'media-'
apply from: file("media/core_settings.gradle")

rootProject.name = "Auxio"
include ':app'
include ':musikr'

// decent-player USB Audio libraries
include ':decent-usb-audio-driver'
include ':decent-usb-audio-wrapper-media3'
include ':decent-media3-decoder-flac'
